/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Napakalaki;
import Model.CombatResult;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Salva
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Creates new form NapakalakiView
     */
    private Napakalaki napakalakiModel;
    public NapakalakiView() {
        initComponents();
    }
    public void setNapakalaki(Napakalaki game)
    {
        napakalakiModel=game;
        jugador.setPlayer(game.getCurrentPlayer());
        mostruo.setMonster(game.getCurrentMonster());
        jugador.setVisible(true);
        combat.setEnabled(false);
        nextTrun.setEnabled(false);
        mostruo.setVisible(false);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView1 = new GUI.MonsterView();
        jugador = new GUI.PlayerView();
        mostruo = new GUI.MonsterView();
        meetMonster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        nextTrun = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meetMonster.setText("Mostrar el Monstruo");
        meetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterActionPerformed(evt);
            }
        });

        combat.setText("Combat");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        nextTrun.setText("Turno siguiente");
        nextTrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTrunActionPerformed(evt);
            }
        });

        resultado.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostruo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(meetMonster)
                        .addGap(95, 95, 95)
                        .addComponent(combat)
                        .addGap(104, 104, 104)
                        .addComponent(nextTrun)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(mostruo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combat)
                    .addComponent(meetMonster)
                    .addComponent(nextTrun))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterActionPerformed
        mostruo.setVisible(true);
        repaint();
        combat.setEnabled(true);
        meetMonster.setEnabled(false);
        jugador.setEnableButton(false);
        repaint();
    }//GEN-LAST:event_meetMonsterActionPerformed

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        CombatResult o = napakalakiModel.developCombat();
        switch(o)
        {
            case WINGAME: 
                resultado.setText("\n\n Â¡Â¡Â¡ H A S   G A N A D O   L A   P A R T I D A !!!");
                break;
            case WIN:
                resultado.setText("\n\n Ganaste el combate");
            break;
            case LOSE:
                resultado.setText("\n\n Has perdido el combate, te toca cumplir el mal rollo");
            break;
            case LOSEANDCONVERT:
                resultado.setText("\n\n Has perdido el combate, pero ahora eres sectario");
            break;
        }
        combat.setEnabled(false);
        nextTrun.setEnabled(true);
        jugador.setEnableButton(true);
        jugador.setPlayer(napakalakiModel.getCurrentPlayer());
        repaint();
    }//GEN-LAST:event_combatActionPerformed

    private void nextTrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTrunActionPerformed
        if (!napakalakiModel.nextTurn())
        {
            JOptionPane.showMessageDialog(null,"Imposible Robar pasar turno falta mal royo por aplicar(si es muerte descarta todo)");
        }
        else
        {
            nextTrun.setEnabled(false);
            meetMonster.setEnabled(true);
            setNapakalaki(napakalakiModel);
        }
        jugador.setPlayer(napakalakiModel.getCurrentPlayer());
        repaint();
    }//GEN-LAST:event_nextTrunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        // Variables Locales
        ArrayList<String> names;
        Napakalaki game = Napakalaki.getInstance();
        NapakalakiView napakalakiView = new NapakalakiView();
        Dice.createInstance(napakalakiView);
        PlayerNamesCapture namesCapture = new PlayerNamesCapture(napakalakiView, true);
        names = namesCapture.getNames();
        game.initGame(names);
        napakalakiView.setNapakalaki(game);
        napakalakiView.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private GUI.PlayerView jugador;
    private javax.swing.JButton meetMonster;
    private GUI.MonsterView monsterView1;
    private GUI.MonsterView mostruo;
    private javax.swing.JButton nextTrun;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
